#ifndef APP_REMOTE_REMOTE_PROTOCOL_H
#define APP_REMOTE_REMOTE_PROTOCOL_H

#define REMOTE_LORA_JOYSTICK_MAX       (2000.0f)
#define REMOTE_LORA_JOYSTICK_DEADBAND  (0.03f)
#define REMOTE_LORA_TIMEOUT_MS         (200u)

#endif
